version: 2
updates:
  # Keep Go module dependencies up to date
  - package-ecosystem: "gomod"
    directory: "src/api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1

  # Keep base Docker image and Dockerfile dependencies up to date
  - package-ecosystem: "docker"
    directory: "src/api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1

  # Keep GitHub Actions workflows up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
